name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: exit if not on master branch
        if: endsWith(github.ref_name, 'master') == false
        run: exit -1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push with tagged name
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sherlock-frontend:${{github.ref_name}}
          push: true
      - name: Build and push with 'latest' tag
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sherlock-frontend:latest
          push: true
